---
name: pr

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
      - run: npm ci
      - run: npm test
        env:
          CI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm run lint
      - run: npm run format

  e2e:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
      - run: npm ci --production
      - run: npm i -g @vercel/ncc
      - run: ncc build main.js -o dist --source-map --license licenses.txt
      - uses: "./"
        with:
          component: "action-e2e"
          github-token: ${{ secrets.GITHUB_TOKEN }}
